FROM node:18-slim

RUN apt-get update && apt-get install -y openssl

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

CMD sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm start"
