# Dockerfile for backend

# Use official Node.js image as base
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port for the backend
EXPOSE 5000

# Start the backend application
CMD ["npm", "run", "prod"]
